server:
  port: 8081

spring:
  application:
    name: schedule-service
  datasource:
    url: jdbc:mysql://localhost:3306/scheduledb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Komal@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


